config/routes.rb
Rails.application.routes.draw do

  get 'events/show'
  root 'landing_pages#index'
  get 'landing_pages/index'
  get '/yolo', to: 'landing_pages#yolo'


  resources :games, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :game_comments
  end

  post 'games/:id', to: 'games#join_game'

  resources :profile, only: [:index, :show, :edit, :update]
  get '/player', to: 'profile#index'
  get '/profil', to: 'profile#edit'
  patch '/profil', to: 'profile#update'

  get '/map', to: 'dashboards#map'

  resources :events

  devise_for :users,
  controllers: {
       confirmations: 'users/confirmations' ,
       omniauth_callbacks: 'users/omniauth_callbacks' ,
       passwords: 'users/passwords' ,
       registrations: 'users/registrations' ,
       sessions: 'users/sessions' ,
       unlocks: 'users/unlocks' }
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user_creator, class_name: "User", optional: true
  belongs_to :user_opponent, class_name: "User", optional: true
  has_many :game_comments

  def address
    [place].compact.join(', ')
  end
  geocoded_by :address

  after_validation :geocode
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @game = Game.new
    @cup = current_user.profile
    if params[:search].present?
      @games_city = Game.near(params[:search], 150).page(params[:page]).per(10)
      @games = Game.all.near([@cup.latitude,@cup.longitude], 150).page(params[:page]).per(10)
    else
    #nerbys(n) n=distance en km
    @games = Game.all.near([@cup.latitude,@cup.longitude], 150).page(params[:page]).per(10)
    end
  end

  def new
    @game = Game.new
  end

  def create
    results = Geocoder.search(params.require(:game)[:place])
    @game = Game.create('place' => params.require(:game)[:place],
                      'date' => params.require(:game)[:date],
                      'description' => params.require(:game)[:description],
                      'game_format' => params.require(:game)[:game_format],
                      'latitude' => results.first.coordinates.first,
                      'longitude' => results.first.coordinates.last,
                      'user_creator_id' => current_user.id)
  
    redirect_to games_path
  end
  
  def show
    @game = Game.find(params[:id])
    @id= params[:id]
  end

  def edit
    @game = Game.find(params[:id])
    @id= params[:id]
  end

  def update
    @game = Game.find(params[:id])
    @game.update(game_params)
    redirect_to game_path(@game.id), :notice => 'Partie modifiée avec succés.'
  end

  def join_game
    @game = Game.find(params[:id])
    if @game.user_opponent_id == current_user.id
        @game.update(user_opponent_id: nil)
        redirect_to game_path(@game.id), :notice => 'Vous avez quitté la partie.'
    else
        @game.update(user_opponent_id: current_user.id)
        redirect_to game_path(@game.id), :notice => 'Vous avez rejoins la partie.'
    end
  end

  def delete
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to '/games'
  end
private
  def game_params
    params.require(:game).permit(:date, :place, :game_format, :description, :user_opponent_id)
  end
  
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/delete.html.erb
<h1>Games#delete</h1>
<p>Find me in app/views/games/delete.html.erb</p>

app/views/games/edit.html.erb
<%= stylesheet_link_tag params[:controller] %>
<div class="wrapper ">
  <%= render 'navbar', :layout => 'navbar' %>
  <%= render 'alert', :layout => 'alert' %>
    <div class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card ">
            <div class="card-header">
              <h4 class="card-title"> Modifier cette partie</h4>
            </div>
                <div class="card-body">
                  <%= form_for @game, url: {action: "update"} do |f| %>
                   <%= f.text_field :date, class: "form-control", placeholder: "Date (JJ/MM/AAAA)" %><br>
                   <%= f.text_field :place, class: "form-control", placeholder: "Lieu" %><br>
                   <%= f.text_field :game_format, class: "form-control", placeholder: "Format joué" %><br>
                   <%= f.text_area :description, class: "form-control", placeholder: "  Description" %><br>
                   <%= f.submit "Modifier cette partie", class: "btn btn-primary" %><br>
                  <% end %>
                </div>
        </div>
    </div>
</div>

app/views/games/index.html.erb
<%= stylesheet_link_tag params[:controller] %>
<div class="wrapper ">
  <%= render 'navbar', :layout => 'navbar' %>
  <div class="content">
    <div class="col-md-12">
      <div class="card card-chart">
        <div class="card-header hover-card-header" onclick="functionReveal()">
          <h3 class="card-title "><i class="tim-icons icon-send text-success "></i>Créer une nouvelle partie</h3>
        </div>
        <div class="card-body text-center"  id="card-hide" style="display:none;">

          <%= form_for @game, url: {action: "create"} do |f| %>
              <%= f.text_field :date, class: "form-control", placeholder: "Date (JJ/MM/AAAA)" %><br>
              <%= f.text_field :place, class: "form-control", placeholder: "Lieu" %><br>
              <%= f.text_field :game_format, class: "form-control", placeholder: "Format joué" %><br>
              <%= f.text_area :description, class: "form-control", placeholder: "  Description" %><br>
              <%= f.submit "Créer une Partie", class: "btn btn-primary" %>
          <% end %>
        
        </div>
      </div>
    </div>
    <!-- end create game -->
    <div class="col-12">
      <% if params[:search].present?%>
      <div class="card ">
        <div class="card-header ">
          <div class="col-12">
            <h3 class="card-title"><i class="tim-icons icon-send text-success "></i> Rechercher une partie</h3>
            <nav class="nav nav-tabs" style="border-bottom:0px">
            <a class="btn btn-sm btn-primary btn-simple" href="#p1" data-toggle="tab">Près de chez vous</a>
            <a class="btn btn-sm btn-primary btn-simple" href="#p2" data-toggle="tab">Par ville</a>
            <a class="btn btn-sm btn-primary btn-simple active" href="#p3" data-toggle="tab">Près de <%= params[:search] %></a>
            </nav>
          </div>
        </div>
        <div class="card-body">
          <div class="tab-content">
            <div class="tab-pane fade" id="p1">
              <div class="table-responsive">
                <table class="table tablesorter" >
                  <thead class=" text-primary">
                    <th>Créateur</th>
                    <th>Lieu</th>
                    <th>Date</th>
                    <th>Format joué</th>
                    <th>Adversaire</th>
                    <th>Distance</th>
                  </thead>
                  <tbody>
                  <%@games.each do |game| %>
                    <tr>
                      <td><% if game.user_creator_id? %>
                              <a href="/profile/<%= game.user_creator_id %>">
                              <%= User.find(game.user_creator_id).profile.username %></a>
                          <% end %>
                      </td>
                      <td><%= game.place %></td>
                      <td><%= game.date.strftime('%d-%m-%Y') %></td>
                      <td><%= game.game_format %></td>
                      <td><% if game.user_opponent_id? %>
                            <a href="/profile/<%= game.user_opponent_id %>">
                            <%= User.find(game.user_opponent_id).profile.username %></a>
                          <% else %>
                            -
                          <% end %>
                      </td>
                      <td><%= game.distance_to([@cup.latitude,@cup.longitude]).round(2)%> kms </td>
                      <td><a href="<%= game_path(game.id) %>" class="btn btn-primary">info</a></td>
                    </tr>
                  <%end%>
                  </tbody>
                </table>
                <div class="container pagination justify-content-center">
                  <%= paginate @games, theme: 'twitter-bootstrap-4'%>
                </div>
              </div>
            </div>
            <div class="tab-pane fade " id="p2">
              <%= form_tag games_path, :method => :get do%>
                <p>
                  <%= text_field_tag :search, params[:search] %>
                  <%= submit_tag "Rechercher", :place => nil, class: "btn btn-primary" %>
                </p>
              <% end%>
            </div>
            <div class="tab-pane fade show active" id="p3">
              <div class="table-responsive">
                <table class="table tablesorter" >
                  <thead class=" text-primary">
                    <th>Créateur</th>
                    <th>Lieu</th>
                    <th>Date</th>
                    <th>Format joué</th>
                    <th>Adversaire</th>
                    <th>Distance</th>
                  </thead>
                  <tbody>
                  <%@games_city.each do |game| %>
                    <tr>
                      <td><% if game.user_creator_id? %>
                              <a href="/profile/<%= game.user_creator_id %>">
                            <%= User.find(game.user_creator_id).profile.username %></a>
                          <% end %>
                      </td>
                      <td><%= game.place %></td>
                      <td><%= game.date.strftime('%d-%m-%Y') %></td>
                      <td><%= game.game_format %></td>
                      <td><% if game.user_opponent_id? %>
                            <a href="/profile/<%= game.user_opponent_id %>">
                            <%= User.find(game.user_opponent_id).profile.username %></a>
                          <% else %>
                            -
                          <% end %>
                      </td>
                      <td><%= game.distance_to(Geocoder.search(params[:search]).first.coordinates).round(2)%> kms </td>
                      <td><a href="<%= game_path(game.id) %>" class="btn btn-primary">info</a></td>
                    </tr>
                  <%end%>
                  </tbody>
                </table>
                <div class="container pagination justify-content-center">
                  <%= paginate @games, theme: 'twitter-bootstrap-4'%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% else%>
      <div class="card ">
        <div class="card-header ">
          <div class="col-12">
            <h3 class="card-title"><i class="tim-icons icon-send text-success "></i> Rechercher une partie</h3>
            <nav class="nav nav-tabs" style="border-bottom:0px">
            <a class="btn btn-sm btn-primary btn-simple active" href="#p1" data-toggle="tab">Près de chez vous</a>
            <a class="btn btn-sm btn-primary btn-simple" href="#p2" data-toggle="tab">Par ville</a>
            </nav>
          </div>
        </div>
        <div class="card-body">
          <div class="tab-content">
            <div class="tab-pane fade show active" id="p1">
              <div class="table-responsive">
                <table class="table tablesorter" >
                  <thead class=" text-primary">
                    <th>Créateur</th>
                    <th>Lieu</th>
                    <th>Date</th>
                    <th>Format joué</th>
                    <th>Adversaire</th>
                    <th>Distance</th>
                  </thead>
                  <tbody>
                  <%@games.each do |game| %>
                    <tr>
                      <td><% if game.user_creator_id? %>
                            <a href="/profile/<%= game.user_creator_id %>">
                            <%= User.find(game.user_creator_id).profile.username %></a> 
                          <% end %>
                      </td>
                      <td><%= game.place %></td>
                      <td><%= game.date.strftime('%d-%m-%Y') %></td>
                      <td><%= game.game_format %></td>
                      <td><% if game.user_opponent_id? %>
                            <a href="/profile/<%= game.user_opponent_id %>">
                            <%= User.find(game.user_opponent_id).profile.username %></a>
                          <% else %>
                           -
                          <% end %>
                      </td>
                      <td><%= game.distance_to([@cup.latitude,@cup.longitude]).round(2)%> kms </td>
                      <td><a href="<%= game_path(game.id) %>" class="btn btn-primary">info</a></td>
                    </tr>
                  <%end%>
                  </tbody>
                </table>
                <div class="container pagination justify-content-center">
                  <%= paginate @games, theme: 'twitter-bootstrap-4'%>
                </div>
              </div>
            </div>
            <div class="tab-pane fade" id="p2">
            <%= form_tag games_path, :method => :get do%>
              <p>
                <%= text_field_tag :search, params[:search] %>
                <%= submit_tag "Rechercher", :place => nil, class: "btn btn-primary" %>
              </p>
            <% end%>
            </div>
          </div>
        </div>
      </div><!-- end search game -->
    <% end%>
  </div>
</div>

app/views/games/new.html.erb
<%= stylesheet_link_tag params[:controller] %>
<div class="wrapper ">
  <%= render 'navbar', :layout => 'navbar' %>
  <div class="content">
    <div class="col-lg-12">
      <div class="card card-chart">
        <div class="card-header ">
          <h3 class="card-title"><i class="tim-icons icon-send text-success "></i> Créer une nouvelle partie :</h3>
        </div>
        <div class="card-body text-center">

          <%= form_for @game, url: {action: "create"} do |f| %>
              <%= f.text_field :date, class: "form-control", placeholder: "Date (JJ/MM/AAAA)" %><br>
              <%= f.text_field :place, class: "form-control", placeholder: "Lieu" %><br>
              <%= f.text_field :game_format, class: "form-control", placeholder: "Format joué" %><br>
              <%= f.text_area :description, class: "form-control", placeholder: "  Description" %><br>
              <%= f.submit "Créer une Partie", class: "btn btn-primary" %>
          <% end %>
        
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/games/show.html.erb
<%= stylesheet_link_tag params[:controller] %>
<div class="wrapper ">
  <%= render 'navbar', :layout => 'navbar' %>
  <%= render 'alert', :layout => 'alert' %>
    <div class="content">
      <div class="row">

      <!-- creator player -->
          <div class="col-md-3">
            <div class="card  card-user">
              <div class="card-body ">
                <p class="card-text">
                  <div class="author">
                    <div class="block block-one"></div>
                    <div class="block block-two"></div>
                    <div class="block block-three"></div>
                    <div class="block block-four"></div>
                    <a href="#">
                      <img class="avatar" src="/assets/anime6.png" alt="...">
                      <h5 class="title"><%= User.find(@game.user_creator_id).profile.username %></h5>
                    </a>
                    <p class="description">
                      Créateur de la partie
                    </p>
                  </div>
                </p>
                <h4 class="card-description text-center">
                de <%= User.find(@game.user_creator_id).profile.city %><br>
                Format préféré : <%= User.find(@game.user_creator_id).profile.favorite_format %><br>
                Couleur de prédilection : <%= User.find(@game.user_creator_id).profile.favorite_color %><br>
                </h4>
              </div>
            </div>
          </div>

    <!-- game -->
        <div class="col-md-4 text-center">
          <i class="fas fa-dice-d20 " style="color:white; font-size:50px; margin-bottom:20px;"></i>
          <div class="card ">
            <div class="card-header">
              <h4 class="card-title float-left"> La partie </h4>
            </div>
            <div class="card-body">
              <h2>Format joué: <%=@game.game_format%></h2><br>
              <h2><i class="fas fa-calendar-alt"></i><%=  @game.date.strftime(' %d-%m-%Y')%></h2> <br>
              <h2><i class="fas fa-map-pin"></i> <%=@game.place%></h2> <br>
              <h3><%=@game.description%></h3>
              <% if @game.user_creator_id == current_user.id %>
                <a href="<%= edit_game_path(@id) %>" class="btn btn-primary">Modifier la partie</a>
                <%= link_to 'Supprimer la partie',  @game,  method: :delete, data: { confirm: 'Voulez vous supprimer la partie ?' }, class: "btn btn-primary"%>
              <% else %>
                  <% if @game.user_opponent_id == nil %>
                      <%= button_to "Rejoindre la partie", game_path(@game), :method => :post, class: "btn btn-primary" %>
                  <% elsif @game.user_opponent_id == current_user.id%>
                      <%= button_to "Quitter la partie", game_path(@game), :method => :post, class: "btn btn-primary" %>
                  <% end %>
              <% end %>
            </div>
          </div>
        </div>

    <!-- opponent player -->
        <div class="col-md-3">
            <div class="card  card-user">
              <div class="card-body ">
              <% if @game.user_opponent_id == nil %>
                <p class="card-text">
                  <div class="author">
                    <div class="block block-one"></div>
                    <div class="block block-two"></div>
                    <div class="block block-three"></div>
                    <div class="block block-four"></div>

                      <i class="avatar fas fa-user-slash" style="color:white; font-size:100px;"></i>
                      <h5 class="title">disponible</h5>

                    <p class="description">
                      Aucun adversaire
                    </p>
                  </div>
                </p>
                <h4 class="card-description text-center">
                </h4>
              <% else %>
                <p class="card-text">
                  <div class="author">
                    <div class="block block-one"></div>
                    <div class="block block-two"></div>
                    <div class="block block-three"></div>
                    <div class="block block-four"></div>
                    <a href="#">
                      <img class="avatar" src="/assets/Jacquouille.jpg" alt="...">
                      <h5 class="title"><%= User.find(@game.user_opponent_id).profile.username %></h5>
                    </a>
                    <p class="description">
                      Adversaire
                    </p>
                  </div>
                </p>
                <h4 class="card-description text-center">
                de <%= User.find(@game.user_opponent_id).profile.city %><br>
                Format préféré : <%= User.find(@game.user_opponent_id).profile.favorite_format %><br>
                Couleur de prédilection : <%= User.find(@game.user_opponent_id).profile.favorite_color %><br>
                </h4>
              <% end %>
              </div>
            </div>
        </div>

      <!-- comments -->
        <div class="col-md-10">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title float-left"> Commentaires : </h4>
            </div>
            <div class="card-body text-center">
                <%= form_with(model: [ @game, @game.game_comments.build ], local: true) do |form| %>
                <p>
                  <%= form.text_field :username, value: current_user.profile.username, class:"form-control" %>
                </p>
                <p>
                  <%= form.text_area :body, class:"form-control" %>
                </p>
                <p>
                  <%= form.submit 'Ajouter un commentaire', class: 'btn btn-primary' %>
                </p>
              <% end %>
            </div>
            <% if @game.game_comments.present? %>
              <% @game.game_comments.each do |comment|%>
                <div class="row comments " style="margin:10px">
                  <div class="col-sm-2 text-center">
                    <img id="profile-photo" src="/assets/Jacquouille.jpg" class="rounded-circle" style="width:50px;" />
                    <h4 class="m-0"><%= comment.username %></h4>
                  </div>
                  <div class="col-sm-6 float-left">
                      <p class="text-white ml-3"><%= comment.created_at %></p>
                      <p class="mb-0 text-white"><%= comment.body%></p>
                  </div>
                </div>
              <% end %>
            <% else %>
            <% end %>
          </div>
        </div>
        <!-- end comments -->
      </div>
    </div>
</div>